### ISSUE TITLE
Wrong Texture - Mortar and Pestle/Goop

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#10]
## Expected Behavior
Different Texture

## Current Behavior
Wrong Texture

## Possible Solution
Fix the Texture

## Steps to Reproduce

1. Use the Goop and Mortar and Pestle
2. SEE
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? yee
Does this happen in multiplayer? yee

## Detailed Description
Wrong Texture

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
Textures are updated with version: `0.21.0.3-Alpha`
