### ISSUE TITLE
Canter Animation Not Working

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#12]
## Expected Behavior
When cantering, use the full canter anim.

## Current Behavior
When cantering, using a broken canter anim.

## Possible Solution
No idea. Its either a blockbench, gecko, or code problem.

## Steps to Reproduce

1. Get on tamed and tacked up horse.
2. Press H once.
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yes

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This is caused by having "post", "pre" or "lerp" in the animation file.
Removing these causes the parts to start moving again.

Somehow, it can still be present in some parts in other animations.
