### ISSUE TITLE
Swimming Animation Not Working

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#13]
## Expected Behavior
When swimming, use swim anim. Im not filling out the rest. Fight me. Version 0.21.0.1-Alpha

## Steps to Reproduce

1.
2.
3.
4.

## Environment Info:
SWEM Version: 
Does this happen in singleplayer?
Does this happen in multiplayer?

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.2-Alpha`
