### ISSUE TITLE
Walk Speed but Trot Animation

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#15]
## Expected Behavior
When walking, use the trot animation. Or if using the trot animation, going at the trot speed.

## Current Behavior
When walking, trotting animation but walking speed.

## Possible Solution
??

## Steps to Reproduce

1. Mount a tamed, tacked up SWEM horse.
2. Press W to walk forward.
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yee

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.21.0.2-Alpha`.
