### ISSUE TITLE
Speed of Horse Broken

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#16]
## Expected Behavior
In whatever gait, expected to go the correct speed.

## Current Behavior
The speed was inc/dec, but the speed was so low it was abnormal.

## Possible Solution
??

## Steps to Reproduce

1. Mount a tamed, tacked up SWEM horse.
2. Press W to walk forward and G/H.
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yee

## Detailed Description
Only happened once, not certain why it happened or how to recreate. Might have hopped on the horse when it was in the super slow walking mode and maybe the gaits did % based off that speed instead of the regular speed?

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This is a issue related to the gravity being disabled, which causes no friction against the ground, resulting in super slow speed.

To fix: Press J twice (let it hover up).

Dev note:
The flight checking, might result in true at some point, where it causes the gravity to disable, but not "fly".

**Comment by MagnusHJensen** [comment]
Could be linked to #18
