### ISSUE TITLE
Getting Kicked Off Horse When Jumped (On Farmland)

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#17]
## Expected Behavior
When a horse walks on farmland, nothing happens. When a horse jumps on farmland, supposed to ruin the farmland like a player does.

## Current Behavior
Horse does not ruin the farmland, the player does when its simultaneously kicked off but still on? Player drops to ground and ruins farmland while not being able to get back on the horse, but other player's view shows the player still on the horse's back. The farmland is not ruined, unless the player drops. (4 out of 5 times this happened).

## Possible Solution
??

## Steps to Reproduce

1. Mount a tamed, tacked up SWEM horse.
2. Jump horse on farmland with other player watching to report their view.
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yee

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This is happening because of the farmland turning into Dirt, while landing.

When the farmland goes into dirt, the voxelshape becomes taller, and most likely kicking you off, resulting in a desync of some sort.

**Comment by MagnusHJensen** [comment]
This is a issue within vanilla MC (Also happens on a fresh mc install, and with vanilla horses) A bug has been reported to Mojang, nothing I can do from here.
Follow the progess at the link below.
https://bugs.mojang.com/browse/MC-225761

**Comment by MagnusHJensen** [comment]
AS stated on the mojang bug report, this will be fixed with 1.17+ per version: `
21w05a`
