### ISSUE TITLE
Suggestion - Saddle Dependency

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#19]
Problem:
Tack just stays on ignoring gravity.

Suggested Solution / Addition:
If I take off the saddle, the girth strap and breast collar should fall to the ground.

How should solution be implemented?:
<--->

Additional Details (If needed):
<--->

**Comment by MagnusHJensen** [comment]
This suggestion has been added with version `1.16.5-0.21.1.3-Alpha`!
