### ISSUE TITLE
Diamond Riding Boot No Lava Walk

### ISSUE THREAD

**Issue by Silverwolf11420** [cavecomputing/SWE-Alpha-Test#20]
**Expected Behavior**
Should be able to lava walk.

**Current Behavior**
When trying to walk on lava, sinks instead. 

**Possible Solution**
No clue

**Steps to Reproduce**
1. Put on diamond riding boots.
2. Walk on lava.

**Environment Info:**
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yee

**Detailed Description
If a crash has happened, provide the logs.**

**Comment by MagnusHJensen** [comment]
Diamond ring boots, does not provide lava walk.

The diamond horse armour provides lava walk for you and your horse.

søn. 25. apr. 2021 02.37 skrev Silverwolf11420 ***@***.***>:
