### ISSUE TITLE
Web Guard & Fence Have no Recipes

### ISSUE THREAD

**Issue by CholitoBuritto26216** [cavecomputing/SWE-Alpha-Test#21]
The web guard (all of them) and the pasture and western fences have no recipes or ways to obtain in survival
## Expected Behavior
There should be a recipe for them

## Current Behavior
There's no recipe

## Possible Solution
Add the recipes

## Steps to Reproduce

1. get the mod "just enough items" or another crafting/inventory mod, and swem
2. Check for a recipe for fences + web guards
3. It doesn't exist
4.

## Environment Info:
SWEM Version: 0.21.1.1
Does this happen in singleplayer? I think so
Does this happen in multiplayer? Yes

## Detailed Description

The recipes just don't exist lol
## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
The recipes has been added with version `1.16.5-0.21.1.2-Alpha`!
