### ISSUE TITLE
Tackbox Glitched

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#23]
Expected Behavior:
Single tack box placed.

Current Behavior:
Two tack boxes placed at the same time directly next to each other.

Possible Solution:
No clue.

Steps to Reproduce:
1: Place a tack box

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

![2021-05-01_20 58 33](https://user-images.githubusercontent.com/83304581/116798870-cf675d80-aac1-11eb-9fbd-1660d43f3fc2.png)

**Comment by MagnusHJensen** [comment]
This is fixed with version `1.16.5-0.21.3.0-Alpha` and up.
