### ISSUE TITLE
Web Guard

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#24]
## Expected Behavior
The web guard is supposed to be able to be placed in the air. Also the textures are supposed to work. 

## Current Behavior
Large and medium WHITE web guard - texture fail
Medium GRAY web guard - texture backwards in one position
Medium LIGHT GRAY web guard - texture backwards in one position
Medium CYAN web guard - texture backwards in one position
Medium PURPLE web guard - texture backwards in one position
Medium BLUE web guard - texture backwards in one position
Medium BROWN web guard - texture backwards in one position
Medium GREEN web guard - texture backwards in one position
Medium RED web guard - texture backwards in one position
Medium BLACK web guard - texture backwards in one position

## Possible Solution
Fix textures (obviously).
For the placing 'in air', maybe make the anchor point for the door to be a side block, not the block below. Like to be able to be placed against the wall so its in the air and doesn't get destroyed unless you break the was

## Steps to Reproduce

1. Place web guard
2. Open web guard
3.
4.

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
The white web guard horse has been added with version: `0.22.6.6-Alpha`.
