### ISSUE TITLE
Horse Jump Animation Locks

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#25]
Expected Behavior: 
Horse jumps with animation then it stops when getting off horse.

Current Behavior:
Horse gets stuck in jumping animation when walking after dismount. Other players cannot see this.

Possible Solution: 
No Clue

Steps to Reproduce:
1: Get on Swem horse level 3 or higher jumping
2: Jump the horse and get off before animation ends

Environment Info:
SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `1.16.5-0.21.2.3-Alpha` and up.
