### ISSUE TITLE
Jumps - List

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#27]
## Expected Behavior
Work

## Current Behavior

ALL DONE FACING EAST/WEST
Basic: 
Right click does not take you backwards when choosing type.
Options listed in ABC order instead of logic order (green, lime green, brown, white, light gray, gray, black, etc).
Be able to face away when placing a jump.
Jump destroys if break the right standard.
If breaks one of the middle pieces, the entire jump is now rendered useless.
"Measurement Tape" is supposed to be "Measurement Tool".

Level 1: 
Log // destroys if no standard (should be able to be placed without standards)
Pole on Box Small // lower hitbox 5 pixels, destroys if no standard (should be able to be placed without standards)  
Pole on Box Large // lower hitbox 3 pixels, destroys if no standard (should be able to be placed without standards)  
Brush Box // lower hitbox 3 pixels, destroys if no standard (should be able to be placed without standards)
Flower Box // broken textures (red), lower hitbox 3 pixels, destroys if no standard (should be able to be placed without standards)
Coop // broken textures, lower hitbox 7 pixels, destroys if no standard (should be able to be placed without standards)
Roll Top // lower hitbox 3 pixels, destroys if no standard (should be able to be placed without standards)
Wall (Mini) // lower hitbox 8 pixels
Ground Pole // broken textures, lower hitbox 13 pixels, destroys if no standard (should be able to be placed without standards), also ground pole places on the same side no matter which side you create the jump from (should that be fixed?)
Rail // lower hitbox 2 pixels, 
Plank // broken model and texture (ends), lower hitbox 2 pixels
Fancy Plank // middle model needs remade and retextured (Hannah)
Cavaletti // missing??

Level 2+:
Cavaletti, Pole on Box (Small, Large), Wall Mini // should no longer be available on layer two and above. 
Panel Wave // texture and model broken (all colors), backwards texture
Panel Arrow // texture and model broken (all colors), backwards texture
Panel Stripe // texture and model broken (all colors), backwards texture

Level 2-4:
Panels are accessible and then inaccessible sometimes? We dont see a pattern

SPECIFIC TO FACING NORTH/SOUTH
Brush Box // The ends are facing the wrong way

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
The jumps have been reworked quite a bit.

I did add cycable buttons, so you can now right click to go backwards on colors and layers.
Also added a seperate block to hold the jump logic, placed 1 block above the upper right standard, which is invisible, so can't be destoryed nor placed over.

**Comment by MagnusHJensen** [comment]
The red missing flower box texture, has been added with version: `0.22.6.3-Alpha`
