### ISSUE TITLE
Horse Walking Animation When Trotting For Other Player

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#28]
Expected Behavior:
Player and other players see proper animation during proper gait.

Current Behavior:
Player sees proper animation while other player sees wrong animation.

Possible Solution:
No clue.

Steps to Reproduce:
1: Go on server with someone
2: Get on SWEM horse
3: Go into trot with other player watching

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
See #15 & #16.
Can this still be reproduced, on a newer version?

**Comment by MagnusHJensen** [comment]
Doesn't seem to be reproducible on newer version.
