### ISSUE TITLE
Horse Armor (Sets)

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#29]
## Current Behavior
Dependency // Horse Armor should not be able to be placed with western or english saddle
Dependency // shouldnt be able to put armor on without all the rest of the tack first
Included // Glow Saddle should come included with all horse armor types (since crafter with it) 

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
All adventure tack and proper dependency for horse armour has been with version: `1.16.5-0.22.2.0-Alpha` and up.
