### ISSUE TITLE
Cantazarite Anvil

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#32]
## Expected Behavior
Name // Cantazarite anvil is supposed to have the name "Cantazarite Anvil"
Hot Box // Appropriate Hit Box

## Current Behavior
Name // Cantazarite Anvil has the name of "swem.container.anvil"
Hot Box // Full Block Hit Box 
Server Crash // Trying to heal diamond boots in C anvil resulted in crash. Crashed @ putting boots in.

## Steps to Reproduce

1. Put non-full healed diamond boots in the C anvil
2.
3.
4.

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by cavecomputing** [comment]
@MagnusHJensen I sent you the log files for today via DM
It's just a zip file named "2021-5-2_log.zip"

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.5-Alpha` and up.

The name is added to the sheet, will be updated once name gen is rerun.
