### ISSUE TITLE
Animations Not Registering

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#34]
## Expected Behavior
All players see all the animations timed properly and in sync.

## Current Behavior
When other players see another player jump with their horse, all they see is a hop, no animation at all.

## Steps to Reproduce

1. Jump on horse.
2. Ask others if they saw it.
3.
4.

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? no
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.4-Alpha` and up.
