### ISSUE TITLE
Tracker doesn't work + no model or texture

### ISSUE THREAD

**Issue by CholitoBuritto26216** [cavecomputing/SWE-Alpha-Test#35]
##It's in the title xD the tracker doesn't work and it doesn't have a model or texture##

## Expected Behavior
It should work and it should have a model and texture

## Current Behavior
The tracker just doesn't DO anything (and no texture or model

## Possible Solution
Uh...... No idea whatsoever

## Steps to Reproduce

1. Get on SWEM
2. Try and use a tracker
3. ~~profit~~ it doesn't do anything
4.

## Environment Info:
SWEM Version: Whatever the latest file is
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yep

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `1.16.5-0.21.2.16-Alpha` and up.
