### ISSUE TITLE
Horse Is Thirsty When Thirst Is Off

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#37]
Expected Behavior:
Horse should not get thirsty since thirst/hunger is off. Should be able to get rid of thirst by being given water bucket or drinking nearby water. 

Current Behavior:
Horse is getting thirsty despite hunger/thirst being off. Cannot canter because too thirsty and cannot get rid of this by giving water to horse with bucket or nearby water.

Possible Solution:
No clue.

Steps to Reproduce:
1: Have tamed SWEM horse
2: Wait for time to pass
3: The horse will eventually become thirsty and unable to canter or stop thirst

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
see #57
