### ISSUE TITLE
Horse Particle Effects Not In Game Yet

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#38]
Expected Behavior:
Particle effects on horse for emotions.

Current Behavior:
No textured particle effects.

Possible Solution:
No clue

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer?  Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
This has been added, but still needs to be rigged up to certain triggers with version: `1.16.5-0.22.5.0-Alpha` and up.
