### ISSUE TITLE
Western Barrels Not In Game

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#39]
Expected Behavior:
Western barrels should be in game.

Current Behavior:
Western barrels are not in game.

Possible Solution:
Add to game.

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
This is added back in with version: `1.16.5-0.21.2.14-Alpha` and up.
