### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#41]
## Current Behavior
Secret items are displayed in the Creative Menu, like the rainbow horse recipe items and the pendant.

## Environment Info:
SWEM Version: 0.21.1.3
Does this happen in singleplayer? idk
Does this happen in multiplayer? yee

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.5-Alpha` and up.
