### ISSUE TITLE
Armor Gold and Up Should Register for Piglins Etc

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#43]
## Expected Behavior
Armor Gold and Up (gold, diamond, amethyst; player, horse) Should Register for Piglins Etc 

## Current Behavior
Piglins, Hoglins, blah blah blah react as if im not wearing anything gold even though all the armor im wearing is laced with it.

## Possible Solution
Add it to some sort of registry or give it the tag it needs? Idk

## Environment Info:
SWEM Version: 0.21.2.5
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.13-Alpha` and up.
