### ISSUE TITLE
Horse Coat Changed To Sweet Boi Overnight

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#44]
Expected Behavior:
Horse coat stays the same as when converted.

Current Behavior:
Horse changed coat to sweet boi overnight.

Possible Solution:
Idk

Steps to Reproduce:
1: Convert a mc horse into swem horse
2: Tame
3: Leave overnight
4: Suddenly sweet boi next day

SWEM Version: swem-1.16.5-0.21.2.5-Alpha
Does this happen in singleplayer? Idk
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
This should be fixed with version: `1.16.5-0.21.2.8-Alpha` and up.
