### ISSUE TITLE
Lapis

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#45]
## Expected Behavior
If right click a horse (that you own), the coat should flip through the 16 available coats. 
// Should be configurable (would make horse servers hell if people could just change their horse's coat color.

## Current Behavior
Nothing

## Environment Info:
SWEM Version: 0.21.2.5
Does this happen in singleplayer? idk
Does this happen in multiplayer? yee

**Comment by MagnusHJensen** [comment]
This has been added with version: `1.16.5-0.21.2.7-Alpha`.

This is a configurable option, which is disabled by default.
