### ISSUE TITLE
Sugar Cube

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#46]
## Expected Behavior
Feed the horse for a couple affinity points once a day and get the good particle effect.

## Current Behavior
Nothin

## Environment Info:
SWEM Version: 0.21.2.5
Does this happen in singleplayer? yee
Does this happen in multiplayer? yee

**Comment by MagnusHJensen** [comment]
This has been added with version: `1.16.5-0.22.5.0-Alpha` and up.
