### ISSUE TITLE
Stall Door Go Bye Bye

### ISSUE THREAD

**Issue by Chestnut-Mum** [cavecomputing/SWE-Alpha-Test#47]
## Steps to Reproduce

1.
2.
3.
4.

## Environment Info:
SWEM Version: 2.11
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yes

When you break stall doors in survival, the door disappears and the item is not dropped. The item should be dropped and needs a breaking time.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.21-Alpha` and up.

All door blocks have gotten a hardness so it isn't a insta break, also the loot tables have been provided so each door should now drop their respective block item.
