### ISSUE TITLE
Horsey no Gallops

### ISSUE THREAD

**Issue by Chestnut-Mum** [cavecomputing/SWE-Alpha-Test#48]
## Environment Info:
SWEM Version: 2.11
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

When you for from a canter to a gallop, the animation dose not trigger and the horses speed dose not increase.

**Comment by MagnusHJensen** [comment]
This was a conflict with the animation name.

This is fixed with the version: `1.16.5-0.21.2.12-Alpha`
