### ISSUE TITLE
Crash When Press E on Back of Horse

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#51]
## Expected Behavior
Be able to see the inventory menu.

## Current Behavior
Client side crash.

## Steps to Reproduce
1. Sit on back of any horse and press E.

## Environment Info:
SWEM Version: 0.21.2.16
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

## If a crash has happened, provide the logs.
[latest.log](https://github.com/cavecomputing/SWE-Alpha-Test/files/6448217/latest.log)

**Comment by MagnusHJensen** [comment]
This should be fixed with version `1.16.5-0.21.2.19-Alpha` and up.
I went a different route with the owner name, which should no longer crash the client.
If a crash happens, please reopen this ticket.
