### ISSUE TITLE
When Jumping With SWEM Boots While In Water Block Of Eater Dissapears

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#52]
Expected Behavior:
Water block stays when jumping in water with swem boots on

Current Behavior:
Water block disappears when jumping in water with swem boots on

Possible Solution:
Idk

Steps to Reproduce:
1: Get on game and put on swem boots of any kind
2: Go in water and try to jump
3: Water block will disappear under you when jumping

SWEM Version: swem-1.16.5-0.21.2.16-Alpha_2
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Yes

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.2.20-Alpha` and up.
