### ISSUE TITLE
Suggestion - No Hurt Anim for Amethyst Boots

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#53]
Problem:
The hurt animation (and sound) plays when landing with the amethyst boots. I dont like it. Its icky. Please make it stop.

Suggested Solution / Addition:
Please make it stop.

How should solution be implemented?:
By stopping.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.21.4.1-Alpha` and up.
