### ISSUE TITLE
Magma Hurts Horse with Amethyst Armor

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#60]
## Current Behavior
Magma hurt the horse when standing on it despite wearing amethyst armor. Took health down quickly, as if not wearing armor at all. All other functions worked as planned.

## Environment Info:
SWEM Version: 0.22.6.0
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.22.6.4-Alpha` and up.
