### ISSUE TITLE
Boots Wont Mend

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#65]
## Expected Behavior
Boots are to mend with Cantazarite, with no cap to how many times it can heal and should not require experience.

## Current Behavior
Tried to heal Amethyst Boots for a second time. I was able to heal all my equipment for the first time, but the boots wouldnt heal. Ill get them more damaged and then try again.

## Steps to Reproduce
1. Not certain

## Environment Info:
SWEM Version: 0.21.4.0
Does this happen in singleplayer? idk
Does this happen in multiplayer? yes

**Comment by MagnusHJensen** [comment]
I can fine heal my Amethyst boots that have taken 400 durability damage, 3 times.

Closing this, as it's not recreatable.
