### ISSUE TITLE
Normal Hitching Posts Don't Drop When Broken

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#67]
Expected Behavior:
Breaking the normal hitching posts will drop the item, giving it back.

Current Behavior:
Breaking hitching posts does not drop item giving item back.

Environment Info:
SWEM Version: swem-1.16.5-0.22.8.1-Alpha
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Idk

**Comment by MagnusHJensen** [comment]
This is fixed with version `1.16.5-0.23.2.2-Alpha` and up.
