### ISSUE TITLE
All Saddles Invisible On Saddle Stand

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#68]
Expected Behavior:
Saddles shown when placed on saddle stand.

Current Behavior:
Saddles do not show when placed on stand.

Environment Info:
SWEM Version: swem-1.16.5-0.22.8.1-Alpha
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Idk

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.24.0.4-Alpha` and up
