### ISSUE TITLE
Cantazarite & amethyst not spawning 

### ISSUE THREAD

**Issue by legalace1** [cavecomputing/SWE-Alpha-Test#72]
Expected Behavior:
To open a Minecraft world and find cantazarite and amethyst 

Current Behavior:
Currently the only ore I can find in game is the star worm lighting ore

SWEM Version: swem-1.16.5-0.24.0.0-Alpha
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Idk

**Comment by MagnusHJensen** [comment]
Can not reproduce.
