### ISSUE TITLE
Pasture fence not connecting properly

### ISSUE THREAD

**Issue by kingterra111** [cavecomputing/SWE-Alpha-Test#73]
![pasture fence glitch](https://user-images.githubusercontent.com/87532919/125956617-a5e8b11b-ce25-401f-bd70-e3da1ae3d46f.PNG)

## Expected Behavior

Fencing should connect to each post correctly

## Current Behavior

the bars that connect to the posts don't connect properly and only go halfway.

## Possible Solution

Not sure, possibly an update issue

## Steps to Reproduce

1. place the pasture fence down on the ground.
2.
3.
4.

## Environment Info:
SWEM Version: 24.0.0
Does this happen in singleplayer? yes
Does this happen in multiplayer? yes

## Detailed Description

The fencing is not connecting properly

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `1.16.5-0.24.0.3-Alpha` and up.
