### ISSUE TITLE
Saddles cannot be placed on saddle racks

### ISSUE THREAD

**Issue by fatherjenny** [cavecomputing/SWE-Alpha-Test#74]
## Expected Behavior

All Saddles should be placeable and removeable from saddle racks

## Current Behavior

English, Western and Adventure saddles cannot be placed on said saddleracks in multiplayer or in single player

## Possible Solution

N/A

## Steps to Reproduce

1. Place a saddle rack on any block
2. Try to place any kind of saddle, and it wont be placed
3.
4.

## Environment Info:
SWEM Version: swem-1.16.5-0.24.0.1-Alpha_1
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Yes

## Detailed Description

All saddles cannot be placed on saddle racks at all

## If a crash has happened, provide the logs.
N/A

**Comment by MagnusHJensen** [comment]
Can not reproduce, the placement of saddles. They don't render as stated in #68
Closed as this is duplicate.
