### ISSUE TITLE
Bridle texture on Bridle Rack broken

### ISSUE THREAD

**Issue by fatherjenny** [cavecomputing/SWE-Alpha-Test#75]
![image](https://user-images.githubusercontent.com/79104449/126047429-dd1767b9-ae77-4181-b76c-d351ab42d020.png)

## Expected Behavior

All Bridles (English, Western, Adventure in all colours) should be able to be placed with their correct textures

## Current Behavior

All Bridles (English, Western, Adventure in all colours) cannot be placed normally on Bridle racks. The texture glitches and has a bunch of white stripes and other texture issues in both singleplayer and multiplayer.

## Possible Solution

Idk remap the texture or gui or something idk

## Steps to Reproduce

1. Place a bridle rack on a block
2. Place any kind of bridle they should all have the same issue, I tested them
3.
4.

## Environment Info:
SWEM Version: swem-1.16.5-0.24.0.1-Alpha_1
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Yes

## Detailed Description

All Bridles (English, Western, Adventure in all colours) cannot be placed normally on Bridle racks. The texture glitches and has a bunch of white stripes and other texture issues in both singleplayer and multiplayer.

## If a crash has happened, provide the logs.

**Comment by Stardust312** [comment]
This is also happening with halters.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.24.0.7-Alpha` and up.
