### ISSUE TITLE
Shavings cannot be stacked

### ISSUE THREAD

**Issue by fatherjenny** [cavecomputing/SWE-Alpha-Test#76]
![image](https://user-images.githubusercontent.com/79104449/126047562-a63dcbb4-5f53-472e-add1-43bdf02134af.png)
![image](https://user-images.githubusercontent.com/79104449/126047586-20efd814-9370-4e52-a0f0-6f7fccd855ef.png)

## Expected Behavior

Both light and dark shavings should be able to be layered on top of one another

## Current Behavior

Both light and dark shavings do not stack, instead they float on the next block upwards

## Possible Solution

N/A

## Steps to Reproduce

1. Place either type of shavings on the ground
2. Try to place another layer on top, it will float.
3.
4.

## Environment Info:
SWEM Version: swem-1.16.5-0.24.0.1-Alpha_1
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Yes

## Detailed Description

Dark and light shavings do not stack as they should, when you place any shaving on top of the other the shaving takes up the next block ontop and appears to be floating

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `1.16.5-0.24.0.2-Alpha` and up.
