### ISSUE TITLE
Horse Doors/Gates don't work

### ISSUE THREAD

**Issue by fatherjenny** [cavecomputing/SWE-Alpha-Test#77]
![image](https://user-images.githubusercontent.com/79104449/126341715-23ce9551-7bb4-4322-ba01-b71f1c17b0aa.png)

## Expected Behavior

Both Care and Horse sized doors/gates/webgaurds should expand across as many blocks as they need to

## Current Behavior

Although care (3 block) doors work, horse sized (2 block) doors, gates, webgaurds only take up one bottom block and do not extent along or upwards as they should.

## Possible Solution

n/a

## Steps to Reproduce

1. Get a (Horse) sized stall door, gate, webgaurd 
2. Place on the ground
3.
4.

## Environment Info:
SWEM Version: swem-1.16.5-0.24.0.1-Alpha
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Yes

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.24.0.5-Alpha` and up.
