### ISSUE TITLE
Cantazarite anvil closes with "e" while renaming

### ISSUE THREAD

**Issue by spiritrider13** [cavecomputing/SWE-Alpha-Test#79]
## Expected Behavior

text is entered and anvil does not close

## Current Behavior

anvil closes

## Possible Solution

bool checking if user is in text box

## Steps to Reproduce

1. enter cantazarite anvil
2. click on text box
3. type e
4. ui closes

## Environment Info:
SWEM Version: 1.16.5-0.24.0.7-Alpha
Does this happen in singleplayer? yes
Does this happen in multiplayer? unknown, assuming yes

## Detailed Description

When renaming an item in the cantazarite anvil, if you type "e", the gui will close even if you are in the name bar.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.24.0.9-Alpha` and up.
