### ISSUE TITLE
Suggestion - Alternate Lead Rope Recipe

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#8]
Problem:
Lead ropes can be super duper annoying to get and theyre necessary to start with horses. I cant even lead a horse home till i have a lead rope, unlike cows which can be lead with wheat etc.

Suggested Solution / Addition:
Alternate lead rope recipe.

How should solution be implemented?:
Lead rope recipe but with SW Goop instead of slime.

Addtional Details (If needed):
<--->

**Comment by MagnusHJensen** [comment]
This recipe has been added with version: `0.21.1.0-Alpha`.
