### ISSUE TITLE
Suggestion - Alternate Blaze Rod Recipes

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#9]
Problem:
Most equestrians don't give a flip about the nether or the end. With the updated Nether, it could be quite the challenge to get blaze rods and makes the mod much less enjoyable for equestrians just trying to START the mod with a cantazarite potion.

Suggested Solution / Addition:
Alternate Blaze Rod recipe

How should solution be implemented?:
Blaze Rod -> Stick, 6 Redstone, Cantazarite, Ender Pearl

Addtional Details (If needed):
<--->

**Comment by MagnusHJensen** [comment]
This recipe has been added with version: `0.21.1.0-Alpha`.
